Baseline cleanup and reorg based on Icosa Open Blocks fork
googlevr/blocks pull request #4
Opened 2024-06-27 18:01 UTC by andybak

2024-06-27 18:46 UTC, ianmacgillivray requested changes

2024-06-27 18:46 UTC, ianmacgillivray commented on Assets/ThirdParty/SteamVR/Editor/SteamVR_Editor.cs
Can't add this, we don't have the rights to open source it

2024-06-27 18:46 UTC, ianmacgillivray commented on open-blocks.sln.DotSettings.user
Is this open-blocks specific? Commit says so.

2024-06-28 18:17 UTC, andybak commented on Assets/ThirdParty/SteamVR/Editor/SteamVR_Editor.cs
As discussed on chat the same files were included in the Tilt Brush repo and the licence allows redistribution - so this is most likely ok.

2024-06-28 18:17 UTC, andybak commented on open-blocks.sln.DotSettings.user
Removed

2024-06-28 20:03 UTC, ianmacgillivray approved these changes

2024-06-28 21:04 UTC, merged